services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./test-artifacts:/tmp/koval-artifacts
      - .:/koval
    devices:
      - /dev/dri/card1:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
