services:
  koval-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: koval-production-server
    ports:
      - "127.0.0.1:8731:8731"
    volumes:
      - koval-db:/koval/db
      - koval-artifacts:/koval/artifacts
    restart: unless-stopped
    environment:
      - RUST_LOG=info

volumes:
  koval-db:
    driver: local
  koval-artifacts:
    driver: local
